### ISSUE TITLE
CVE-2023-4863 possibly affecting webp-imageio?

### ISSUE THREAD

**Issue by fgrilli** [usefulness/webp-imageio#131]
Hello, 

according to https://www.cve.org/CVERecord?id=CVE-2023-4863 versions of libwebp from 0.5 to 1.3.2 (excluding) are affected by heap buffer overflow issue.
If I'm not mistaken, latest webp-imageio uses precisely version 1.3.1 of that library.

**Comment by mateuszkwiecinski** [comment]
Yup, you're right. This library is bundled with version 1.3.1 of libwebp. I tried to build new images, but the pipeline [broke](https://github.com/usefulness/webp-imageio/actions/runs/6244196777/job/16951588649) and I'll have to (having almost zero experience with docker) spend some time debugging the reason behind
>docker: failed to register layer: write /usr/lib/gcc-cross/arm-linux-gnueabi/10/lto1: no space left on device.

Wish me luck! 🤞

**Comment by fgrilli** [comment]
> Yup, you're right. This library is bundled with version 1.3.1 of libwebp. I tried to build new images, but the pipeline [broke](https://github.com/usefulness/webp-imageio/actions/runs/6244196777/job/16951588649) and I'll have to (having almost zero experience with docker) spend some time debugging the reason behind
> 
> > docker: failed to register layer: write /usr/lib/gcc-cross/arm-linux-gnueabi/10/lto1: no space left on device.
> 
> Wish me luck! 🤞

Thanks a lot for your quick reaction! 🙏

**Comment by mateuszkwiecinski** [comment]
[v0.5.0](https://github.com/usefulness/webp-imageio/releases/tag/v0.5.0) has been released which should contain binaries built from [v1.3.2](https://chromium.googlesource.com/webm/libwebp/+/refs/tags/v1.3.2) tag.  

Thanks you for bringing the issue to my attention, I missed that Internet got broken recently 😅

**Comment by fgrilli** [comment]
> [v0.5.0](https://github.com/usefulness/webp-imageio/releases/tag/v0.5.0) has been released which should contain binaries built from [v1.3.2](https://chromium.googlesource.com/webm/libwebp/+/refs/tags/v1.3.2) tag.
> 
> Thanks you for bringing the issue to my attention, I missed that Internet got broken recently 😅

Thanks again for fixing this! 
Hopefully it's not asking much but would it be possible to release a 0.4.2 patch version without this [breaking change](https://github.com/usefulness/webp-imageio/pull/120)?
Our codebase still requires Java 1.8 and after updating to v0.5.0 we're getting lots of
`java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO` 💥
